### ISSUE TITLE
_lzma.LZMADecompressor' object has no attribute 'needs_input

### ISSUE THREAD

**Issue by harirajeev** [GRAAL-Research/deepparse-address-data#2]
compress_pickle.load("at.lzma", compression="lzma")

Is throwing an error 

AttributeError: '_lzma.LZMADecompressor' object has no attribute 'needs_input

Running on Python 3.8 in a Linux machine

Have you faced this issue before ?  Thanks

**Comment by MAYAS3** [comment]
Hello @harirajeev,

Are you still encountering issues with the decompression?

So sorry about the delay, this issue sort of fell through the cracks.
